_BASE_: "faster_rcnn_R_50_FPN_sup10_run1-base.yaml"
SEMISUPNET:
  UNSUP_LOSS_WEIGHT_REG: 1.0
  IOU_PRED_INFERENCE_THRESHOLD: 0.4
  IOU_PRED_THRESHOLD: 0.75
  WITH_IOU_PRED: True
  WITH_IOU_PRED_ELU: True
