_BASE_: "faster_rcnn_R_50_FPN_sup10_run1-base.yaml"
SEMISUPNET:
  IOU_PRED_THRESHOLD: 0.75
  IOU_PRED_INFERENCE_THRESHOLD: 0.5
  #DEBUG_BBOX_LABELS: True
  WITH_IOU_PRED: True
  WITH_BBOX_IOU_REGRES: True
  USE_SMOOTHL1: True
